[package]
name = "get_grains"
version = "0.1.0"
authors = ["Alexander Thaller <alexander.thaller@trivago.com>"]

[dependencies]
error-chain = "0.10.0"
log = "0.3"
loggerv = "0.2"
regex = "0.2"
serde_json = "0.9"

[dependencies.clap]
version = "2"
features = ["yaml"]
